<?php

/**
 * Removes stylesheets that plugins load on the public site even though
 * visitors never use them. Each one is render-blocking, which hurts
 * mobile FCP/LCP the most (slow 4G makes every extra request expensive).
 *
 * - dashicons: the WordPress admin icon font.
 * - wp-components: the block editor's UI styles (panels, modals, sidebar
 *   controls). Not needed to display blocks; front-end block styles live
 *   in wp-block-library and the wp-block-* inline styles.
 *
 * Logged-in users keep both, since the admin bar and any front-end
 * editing tools may rely on them.
 *
 * If a stylesheet keeps showing up after this, another stylesheet lists
 * it as a dependency and WordPress re-adds it; find that plugin before
 * removing anything else.
 */
function adeptbuild_dequeue_unused_styles() {
	if ( is_user_logged_in() ) {
		return;
	}

	$handles = array(
		'dashicons',
		'wp-components',
	);

	foreach ( $handles as $handle ) {
		wp_dequeue_style( $handle );
	}
}
add_action( 'wp_enqueue_scripts', 'adeptbuild_dequeue_unused_styles', 100 );

/**
 * Lazy-loads every image in the front page content.
 *
 * WordPress only adds loading="lazy" automatically to images that have
 * width and height attributes, and the home page images live in custom
 * HTML blocks without them, so all of them (rotating "We Build"
 * backgrounds, service strips, CTA photo) were downloaded on page load.
 * Everything in the content sits below the video hero, so none of these
 * images is the LCP element and all of them can wait until scrolled near.
 *
 * @param string $img     Full <img> tag.
 * @param string $context Where the tag comes from.
 * @return string
 */
function adeptbuild_lazy_home_content_images( $img, $context ) {
	if ( 'the_content' !== $context || ! is_front_page() ) {
		return $img;
	}
	if ( false === strpos( $img, ' loading=' ) ) {
		$img = str_replace( '<img ', '<img loading="lazy" ', $img );
	}
	return $img;
}
add_filter( 'wp_content_img_tag', 'adeptbuild_lazy_home_content_images', 10, 2 );

/**
 * LocalBusiness structured data for Adept Builders & Design.
 *
 * Instead of printing a separate JSON-LD block (which would create a second
 * organization entity competing with Yoast's), this extends the Organization
 * node Yoast already outputs and also types it as HomeAndConstructionBusiness.
 * Everything stays in a single graph under the same @id.
 *
 * Requirement: Yoast SEO → Settings → Site representation must be set to
 * "Organization", with a name and logo. If it is set to "Person", this
 * filter never runs.
 *
 * @package Adeptbuild
 */
 
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
 
/**
 * Adds local business details to Yoast's Organization schema node.
 *
 * @param array $data Organization schema data generated by Yoast.
 * @return array
 */
function adeptbuild_local_business_schema( $data ) {
 
	$data['@type'] = array( 'Organization', 'HomeAndConstructionBusiness' );
 
	// Core business details.
	$data['name']      = 'Adept Builders & Design';
	$data['url']       = home_url( '/' );
	$data['telephone'] = '+1-800-611-1776';
	$data['email']     = 'office@adeptbuild.com';
 
	// Reuse the logo Yoast already registers instead of duplicating it.
	$data['image'] = array( '@id' => home_url( '/#/schema/logo/image/' ) );
 
	// Office address. Must match Google Business Profile, Yelp, Houzz and the site footer exactly.
	$data['address'] = array(
		'@type'           => 'PostalAddress',
		'streetAddress'   => '14431 Ventura Blvd. #440',
		'addressLocality' => 'Sherman Oaks',
		'addressRegion'   => 'CA',
		'postalCode'      => '91423',
		'addressCountry'  => 'US',
	);
 
	$data['geo'] = array(
		'@type'     => 'GeoCoordinates',
		'latitude'  => 34.152454925373576,
		'longitude' => -118.44706016932098,
	);
 
	$data['hasMap'] = 'https://maps.app.goo.gl/sjiqM4j4wsw2fgWx5';
 
	// Business hours. Assumes Monday to Friday; add 'Saturday' / 'Sunday' if needed.
	$data['openingHoursSpecification'] = array(
		array(
			'@type'     => 'OpeningHoursSpecification',
			'dayOfWeek' => array( 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday' ),
			'opens'     => '09:00',
			'closes'    => '17:00',
		),
	);
 
	// Contact points: main phone line and the text-message line.
	$data['contactPoint'] = array(
		array(
			'@type'             => 'ContactPoint',
			'telephone'         => '+1-800-611-1776',
			'email'             => 'office@adeptbuild.com',
			'contactType'       => 'customer service',
			'areaServed'        => 'US',
			'availableLanguage' => 'English',
		),
		array(
			'@type'       => 'ContactPoint',
			'telephone'   => '+1-818-579-2578',
			'contactType' => 'sales',
			'description' => 'Text messages',
		),
	);
 
	// Service area. Cities mentioned across the site; edit as needed.
	$cities = array(
		'Los Angeles',
		'Sherman Oaks',
		'Santa Monica',
		'West Hollywood',
		'Hollywood',
		'Bel Air',
		'Burbank',
		'Pasadena',
		'Calabasas',
		'Agoura Hills',
		'Malibu',
		'Torrance',
	);
	$data['areaServed'] = array_map(
		function ( $city ) {
			return array(
				'@type' => 'City',
				'name'  => $city . ', CA',
			);
		},
		$cities
	);
 
	// Services, each linked to its landing page. Update the paths if any URL changes.
	$services = array(
		'Full Home Renovation'    => '/full-home-renovations/',
		'ADUs & Home Additions'   => '/adus/',
		'Deck Construction'       => '/decking/',
		'Custom Pools'            => '/custom-pools/',
		'Pergolas & Patio Covers' => '/pergola/',
		'Landscape Design'        => '/landscape-design/',
	);
	$offers = array();
	foreach ( $services as $name => $path ) {
		$offers[] = array(
			'@type'       => 'Offer',
			'itemOffered' => array(
				'@type' => 'Service',
				'name'  => $name,
				'url'   => home_url( $path ),
			),
		);
	}
	$data['hasOfferCatalog'] = array(
		'@type'           => 'OfferCatalog',
		'name'            => 'Design-Build Services',
		'itemListElement' => $offers,
	);
 
	$data['founder'] = array(
		'@type' => 'Person',
		'name'  => 'Lior Ohayon',
	);
 
	// Official profiles, merged with any already set in Yoast → Site representation.
	$profiles = array(
		'https://www.facebook.com/adeptbuild',
		'https://www.instagram.com/adept_builders/',
		'https://www.yelp.com/biz/adept-builders-and-design-sherman-oaks',
		'https://www.houzz.com/professionals/design-build-firms/adept-builders-and-design-pfvwus-pf~29209487',
	);
	$existing       = isset( $data['sameAs'] ) ? (array) $data['sameAs'] : array();
	$data['sameAs'] = array_values( array_unique( array_merge( $existing, $profiles ) ) );
 
	/*
	 * Optional fields, not set yet:
	 * - 'priceRange'   => '$$$$'
	 * - 'foundingDate' => 'YYYY'
	 * - 'identifier'   => CSLB license number, if one is ever provided.
	 */
 
	return $data;
}
add_filter( 'wpseo_schema_organization', 'adeptbuild_local_business_schema' );

define( 'ADEPTBUILD_VERSION', '1.8.3' );

/**
 * Basic theme setup.
 */
function adeptbuild_setup() {

	load_theme_textdomain( 'adeptbuild', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support( 'editor-styles' );

	add_theme_support(
		'html5',
		array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script', 'navigation-widgets' )
	);

	add_theme_support(
		'custom-logo',
		array(
			'height'      => 70,
			'width'       => 260,
			'flex-height' => true,
			'flex-width'  => true,
		)
	);

	register_nav_menus(
		array(
			'primary-menu' => __( 'Primary Menu', 'adeptbuild' ),
			'footer-menu'  => __( 'Footer Menu', 'adeptbuild' ),
			'legal-menu'   => __( 'Legal Menu (bottom bar)', 'adeptbuild' ),
		)
	);

	// Color palette available in the block editor.
	add_theme_support(
		'editor-color-palette',
		array(
			array(
				'name'  => __( 'Signal Blue', 'adeptbuild' ),
				'slug'  => 'primary',
				'color' => '#1046BB',
			),
			array(
				'name'  => __( 'Cyan', 'adeptbuild' ),
				'slug'  => 'aqua',
				'color' => '#57E1F3',
			),
			array(
				'name'  => __( 'Charcoal', 'adeptbuild' ),
				'slug'  => 'deep',
				'color' => '#1A1A1A',
			),
			array(
				'name'  => __( 'Cyan Accent', 'adeptbuild' ),
				'slug'  => 'accent',
				'color' => '#57E1F3',
			),
			array(
				'name'  => __( 'Light Gray', 'adeptbuild' ),
				'slug'  => 'surface-alt',
				'color' => '#F6F9FA',
			),
			array(
				'name'  => __( 'White', 'adeptbuild' ),
				'slug'  => 'white',
				'color' => '#FFFFFF',
			),
		)
	);
}
add_action( 'after_setup_theme', 'adeptbuild_setup' );

/**
 * Tells the browser the real rendered width of the header logo.
 *
 * WordPress outputs sizes="(max-width: 2558px) 100vw, 2558px" for the custom
 * logo, so the browser downloads the full-size file even though the logo is
 * displayed at roughly 260px. The logo is the LCP element on the home page,
 * so this directly affects LCP. Adjust the values if the logo width changes.
 *
 * @param array $attr Custom logo image attributes.
 * @return array
 */
function adeptbuild_custom_logo_sizes( $attr ) {
	$attr['sizes']         = '(max-width: 768px) 180px, 260px';
	$attr['fetchpriority'] = 'high';
	unset( $attr['loading'] );
	return $attr;
}
add_filter( 'get_custom_logo_image_attributes', 'adeptbuild_custom_logo_sizes' );

/**
 * Content width (used by WordPress for embeds and images).
 */
function adeptbuild_content_width() {
	$GLOBALS['content_width'] = apply_filters( 'adeptbuild_content_width', 1200 );
}
add_action( 'after_setup_theme', 'adeptbuild_content_width', 0 );

/**
 * Styles and scripts.
 */
function adeptbuild_scripts() {

	// The only web font is Quicksand, self-hosted via @font-face in style.css.
	wp_enqueue_style( 'adeptbuild-style', get_stylesheet_uri(), array(), ADEPTBUILD_VERSION );

	wp_enqueue_script(
		'adeptbuild-navigation',
		get_theme_file_uri( '/assets/js/navigation.js' ),
		array(),
		ADEPTBUILD_VERSION,
		true
	);

	// Only where the content actually has a YouTube embed (none of the
	// static pages do — mostly blog posts).
	if ( is_singular() && false !== stripos( (string) get_post_field( 'post_content', get_queried_object_id() ), 'youtu' ) ) {
		wp_enqueue_script(
			'adeptbuild-lite-embed',
			get_theme_file_uri( '/assets/js/lite-embed.js' ),
			array(),
			ADEPTBUILD_VERSION,
			true
		);
	}

	if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
		wp_enqueue_script( 'comment-reply' );
	}
}
add_action( 'wp_enqueue_scripts', 'adeptbuild_scripts' );

/**
 * Preloads Quicksand — every element on the site uses it, so the browser
 * shouldn't wait until it parses style.css to discover it.
 */
function adeptbuild_preload_font() {
	printf(
		'<link rel="preload" href="%s" as="font" type="font/woff2" crossorigin>' . "\n",
		esc_url( get_theme_file_uri( '/assets/fonts/Quicksand.woff2' ) )
	);
}
add_action( 'wp_head', 'adeptbuild_preload_font', 1 );

/**
 * Widget areas.
 */
function adeptbuild_widgets_init() {

	register_sidebar(
		array(
			'name'          => __( 'Blog Sidebar', 'adeptbuild' ),
			'id'            => 'sidebar-1',
			'description'   => __( 'Shown on blog posts and archives.', 'adeptbuild' ),
			'before_widget' => '<section id="%1$s" class="widget %2$s">',
			'after_widget'  => '</section>',
			'before_title'  => '<h3 class="widget-title">',
			'after_title'   => '</h3>',
		)
	);

	for ( $i = 1; $i <= 2; $i++ ) {
		register_sidebar(
			array(
				/* translators: %d: column number. */
				'name'          => sprintf( __( 'Footer Column %d', 'adeptbuild' ), $i ),
				'id'            => 'footer-' . $i,
				'description'   => __( 'Middle columns of the footer.', 'adeptbuild' ),
				'before_widget' => '<section id="%1$s" class="widget %2$s">',
				'after_widget'  => '</section>',
				'before_title'  => '<h3 class="widget-title">',
				'after_title'   => '</h3>',
			)
		);
	}
}
add_action( 'widgets_init', 'adeptbuild_widgets_init' );

/**
 * Excerpt length and "read more" marker.
 */
function adeptbuild_excerpt_length() {
	return 24;
}
add_filter( 'excerpt_length', 'adeptbuild_excerpt_length' );

function adeptbuild_excerpt_more() {
	return '&hellip;';
}
add_filter( 'excerpt_more', 'adeptbuild_excerpt_more' );

/**
 * Extra body classes so styles can be fine-tuned.
 */
function adeptbuild_body_classes( $classes ) {
	if ( ! is_active_sidebar( 'sidebar-1' ) || is_page() || is_front_page() ) {
		$classes[] = 'ab-no-sidebar';
	}
	if ( is_front_page() ) {
		$classes[] = 'ab-home';
	}
	return $classes;
}
add_filter( 'body_class', 'adeptbuild_body_classes' );

/**
 * Adds ARIA attributes to primary menu links that open a dropdown.
 */
function adeptbuild_menu_link_attributes( $atts, $item, $args ) {
	if ( isset( $args->theme_location ) && 'primary-menu' === $args->theme_location
		&& in_array( 'menu-item-has-children', (array) $item->classes, true ) ) {
		$atts['aria-haspopup'] = 'true';
		$atts['aria-expanded'] = 'false';
	}
	return $atts;
}
add_filter( 'nav_menu_link_attributes', 'adeptbuild_menu_link_attributes', 10, 3 );

require_once get_template_directory() . '/inc/template-tags.php';
require_once get_template_directory() . '/inc/customizer.php';
require_once get_template_directory() . '/inc/meta-boxes.php';
require_once get_template_directory() . '/inc/class-mega-menu-walker.php';
require_once get_template_directory() . '/inc/home-intro.php';
